export default {
	extends: 'stylelint-config-standard',
	ignoreFiles: [
		'node_modules/**/*.*',
		'docs/*.*',
	],
	rules: {
		'alpha-value-notation': null,
		'annotation-no-unknown': true,
		'at-rule-no-unknown': true,
		'color-hex-length': null,
		'color-no-invalid-hex': true,
		'comment-empty-line-before': null,
		'custom-property-empty-line-before': null,
		'custom-property-no-missing-var-function': true,
		'declaration-block-no-duplicate-custom-properties': true,
		'declaration-block-no-duplicate-properties': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'declaration-block-single-line-max-declarations': 3,
		'declaration-empty-line-before': null,
		'font-family-no-duplicate-names': true,
		'font-family-no-missing-generic-family-keyword': true,
		'function-calc-no-unspaced-operator': true,
		'function-linear-gradient-no-nonstandard-direction': true,
		'function-name-case': 'lower',
		'function-no-unknown': true,
		'length-zero-no-unit': true,
		'media-feature-name-no-unknown': true,
		'no-descending-specificity': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'no-invalid-double-slash-comments': true,
		'no-invalid-position-at-import-rule': true,
		'no-irregular-whitespace': true,
		'no-unknown-animations': true,
		'number-max-precision': 10,
		'property-no-unknown': true,
		'property-no-vendor-prefix': null,
		'rule-empty-line-before': null,
		'selector-attribute-quotes': null,
		'selector-pseudo-class-no-unknown': true,
		'selector-pseudo-element-colon-notation': 'double',
		'selector-pseudo-element-no-unknown': true,
		'selector-type-case': 'lower',
		'selector-type-no-unknown': true,
		'shorthand-property-no-redundant-values': true,
		'string-no-newline': true,
		'unit-no-unknown': true,
		'value-keyword-case': 'lower',
		'value-no-vendor-prefix': null
	}
};
