export declare const icons: {
    adjustments: string;
    alert: string;
    apps: string;
    archive: string;
    arrowLeft: string;
    arrowNarrowDown: string;
    arrowNarrowUp: string;
    arrowRight: string;
    bank: string;
    basket: string;
    bell: string;
    book: string;
    bookmark: string;
    calculator: string;
    calendar: string;
    cart: string;
    cash: string;
    chartLine: string;
    chartPie: string;
    check: string;
    checkbox: string;
    checkboxChecked: string;
    checkCircle: string;
    checklist: string;
    chevronLeft: string;
    chevronRight: string;
    circle: string;
    clock: string;
    close: string;
    cog: string;
    coin: string;
    copy: string;
    dots: string;
    edit: string;
    envelope: string;
    error: string;
    eye: string;
    eyeOff: string;
    filter: string;
    folder: string;
    help: string;
    home: string;
    info: string;
    link: string;
    list: string;
    logout: string;
    math: string;
    meatballs: string;
    minusCircle: string;
    moon: string;
    plus: string;
    plusCircle: string;
    print: string;
    receipt: string;
    redo: string;
    refresh: string;
    repeat: string;
    reportAnalytics: string;
    reportMoney: string;
    search: string;
    shared: string;
    sidebarLeft: string;
    sidebarRight: string;
    sortAsc: string;
    sortDesc: string;
    split: string;
    star: string;
    sun: string;
    tag: string;
    trash: string;
    undo: string;
    user: string;
    users: string;
};
type IconsType = {
    [key: string]: string;
};
export declare const customIcons: IconsType;
export declare function getIcon(name: string): string;
export declare function addIcon(name: string, svg: string): void;
export {};
//# sourceMappingURL=icons.d.ts.map